apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-dockerfile
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:ilyagorban-codefresh/sample-dockerfile.git'
    path: helm
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      releaseName: sample-dockerfile
  destination:
    namespace: applications
    name: sample-dockerfile
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
