# service:
#   type: LoadBalancer
image:
  repository: gcr.io/ilyagorban-org/sample
  tag: a8625b6
  pullPolicy: Always
tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "application"
  effect: "NoSchedule"
