# service:
#   type: LoadBalancer
image:
  repository: ilyag/python-app
  tag: abcd
  pullPolicy: Always
tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "application"
  effect: "NoSchedule"
